{{- if .Values.encryptedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "pihole.fullname" . }}
  labels: {{ include "pihole.labels" . | nindent 4 }}
spec:
  encryptedData:
  {{- range $key, $value := .Values.encryptedSecrets }}
    {{ $key }}: {{ $value }}
  {{- end }}
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: {{ .Release.Name | quote }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}
      name: {{ template "pihole.fullname" . }}
      namespace: {{ .Release.Namespace }}
      labels: {{ include "pihole.labels" . | nindent 8 }}
    type: Opaque
{{- end }}