{{- if not .Values.encryptedSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pihole.fullname" . }}
  labels: {{ include "pihole.labels" . | nindent 4 }}
type: Opaque
data:
  WEBPASSWORD: {{ randAlphaNum 40 | b64enc | quote }}
{{- end }}