name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Helm 3
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      - name: Provide SSH private key
        env: 
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY }}"

      - name: Create Chart and upload to helm_chart repository
        run: |
          CHART=`echo $GITHUB_REPOSITORY | grep -oP '(?<=KonKube\/).*(?=_)'`
          VERSION=`cat $CHART/Chart.yaml | grep -oP '(?<=version:\s).*'`
          helm package $CHART
          git clone git@github.com:KonKube/helm_charts.git
          mv $CHART-$VERSION.tgz ./helm_charts
          cd ./helm_charts
          git config user.name github-konkube-actions
          git config user.email info.konkube@gmail.com
          git add $CHART-$VERSION.tgz
          git commit -m "Added $CHART-$VERSION.tgz"
          git push
          
